# Generated by Django 3.1.6 on 2023-09-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_currency', models.CharField(max_length=255, verbose_name='Название валюты')),
                ('uid_currency', models.CharField(max_length=255, unique=True, verbose_name='Название валюты')),
            ],
            options={
                'verbose_name': 'Список валют',
                'verbose_name_plural': 'Список валют',
                'ordering': ('name_currency',),
            },
        ),
    ]
